-- Criar tabelas

USE [Lista 1]

CREATE TABLE COSTUMER (
	CDCUSTOMER INTEGER,
	NMCUSTOMER VARCHAR(255),
	NRFONE NUMERIC(12),
	DSADRESS VARCHAR(255)
)

CREATE TABLE REQUEST(
	CDREQUEST INTEGER,
	DTREQUEST DATE,
	CDCOSTUMER INTEGER,
	DTDELIVER DATE,
	VLTOTAL INTEGER
)

CREATE TABLE PRODUCTREQUEST (
	CDREQUEST INTEGER,
	CDPRODUCT INTEGER,
	QTDAMOUNT INTEGER,
	VLUNITARY NUMERIC(10,2),
)

CREATE TABLE PRODUCT (
	CDPRODUCT INTEGER,
	NMPRODUCT VARCHAR(255),
	CDSUPPPLIER INTEGER,
	VLPRICE MONEY,
	QTSTOCK INTEGER
)

CREATE TABLE SUPPLIER (
	CDSUPPLIER INTEGER,
	NMSUPPLIER VARCHAR(255),
	NRFONE NUMERIC(12)
)

--Inserir not nulls
ALTER TABLE COSTUMER 
ALTER COLUMN NMCUSTOMER VARCHAR (255) NOT NULL
ALTER COLUMN NRFONE NUMERIC(12) NOT NULL
ALTER COLUMN DSADRESS VARCHAR(255) NOT NULL

ALTER TABLE PRODUCT
ALTER COLUMN NMPRODUCT VARCHAR (255) NOT NULL
ALTER COLUMN VLPRICE MONEY  NOT NULL
ALTER COLUMN QTSTOCK INTEGER NOT NULL

ALTER TABLE REQUESTPRODUCT
ALTER COLUMN QTAMOUNT INTEGER NOT NULL
ALTER COLUMN VLUNITARY NUMERIC(10,2) NOT NULL

ALTER TABLE REQUEST
ALTER COLUMN DTREQUEST DATE NOT NULL
ALTER COLUMN DTDELIVER DATE NOT NULL
ALTER COLUMN VLTOTAL INTEGER NOT NULL

ALTER TABLE SUPPLIER
ALTER COLUMN NMSUPPLIER VARCHAR(255) NOT NULL
ALTER COLUMN NRFONE NUMERIC(12) NOT NULL


--Inserir chaves primarias

USE [Lista 1]

ALTER TABLE CUSTOMER 
ADD PRIMARY KEY (CDCUSTOMER)

ALTER TABLE REQUEST 
ADD PRIMARY KEY (CDREQUEST)

ALTER TABLE PRODUCT
ADD PRIMARY KEY (CDPRODUCT)

ALTER TABLE SUPPLIER
ADD PRIMARY KEY (CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST
ADD PRIMARY KEY (CDREQUEST, CDPRODUCT)

--inserir chaves estrangeiras

USE [Lista 1]

ALTER TABLE REQUEST 
ADD CONSTRAINT FK_COSTUMER FOREIGN KEY (CDCOSTUMER) REFERENCES COSTUMER(CDCUSTOMER)

ALTER TABLE PRODUCT 
ADD CONSTRAINT FK_SUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_REQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST)