SELECT * FROM CUSTOMER
SELECT * FROM SUPPLIER


--listar nome e telefone de todos q o telefone inicia com 4
SELECT NMCUSTOMER, IDFONE FROM CUSTOMER
WHERE IDFONE LIKE '4%'

--listar todas as colunas dos clientes q não tem telefone cadastrado
SELECT CDCUSTOMER, NMCUSTOMER, IDFONE, NMADRESS 
FROM CUSTOMER
WHERE IDFONE=null

--listar suppliers que não tem o DDD no telefone
SELECT NMSUPPLIER, IDFONE FROM SUPPLIER
WHERE LEN(IDFONE) < 8

--listar product com 10% de desc onde estoque>2000
SELECT NMPRODUCT, QTSTOCK, (VLPRICE-(VLPRICE* 0.1)) AS VLDESCT
FROM PRODUCT
WHERE QTSTOCK > 2000

--listar products com preço entre 10 e 20 reais
SELECT NMPRODUCT, VLPRICE 
FROM PRODUCT 
WHERE VLPRICE BETWEEN 10 AND 20

--listar total estoque dos produtos que preço > 50
SELECT NMPRODUCT, VLPRICE, (VLPRICE * QTSTOCK) AS TOTALESTOCK 
FROM PRODUCT 
WHERE VLPRICE > 50

--listar produto e supplier com preço>20 e qtd>1500
SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
WHERE VLPRICE > 20 AND QTSTOCK > 1500

--listar valortotal, nome do costumer e data dos pedidos de junho a julho de 2003
SELECT CUSTOMER.NMCUSTOMER,REQUEST.DTREQUEST, REQUEST.VLTOTAL
FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER=CUSTOMER.CDCUSTOMER
WHERE DTREQUEST BETWEEN '2003-06-01' AND '2003-07-31'

--listar nome costumer, nome product, data request, qtd amount, valor unitario, total request se a qtd do pedido > 500
SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, REQUEST.DTREQUEST, PRODUCTREQUEST.QTAMOUNT, PRODUCTREQUEST.VLUNITARY, ( PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS TOTALREQUEST
FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER=REQUEST.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST=PRODUCTREQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT=PRODUCT.CDPRODUCT
WHERE PRODUCTREQUEST.QTAMOUNT > 500