--A
DELETE FROM REQUEST

WHERE (VLTOTAL) < 1000
AND (REQUEST.DTREQUEST) BETWEEN '2003-06-01' AND '2003-06-30'
AND CDREQUEST NOT IN(SELECT DISTINCT CDREQUEST FROM PRODUCTREQUEST);

--B
UPDATE P
SET VLPRICE = (SELECT AVG(P.VLPRICE)
    FROM REQUEST R
    INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST
    INNER JOIN PRODUCT P ON PR.CDPRODUCT = P.CDPRODUCT
    WHERE (P.QTSTOCK) - (PR.QTAMOUNT) < 800)
FROM PRODUCT P
INNER JOIN PRODUCTREQUEST PR ON P.CDPRODUCT = PR.CDPRODUCT
INNER JOIN REQUEST R ON PR.CDREQUEST = R.CDREQUEST
WHERE (P.QTSTOCK) - (PR.QTAMOUNT) < 800;

--C
 INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, IDFONE, NMADRESS)
 SELECT ( SELECT MAX(CDCUSTOMER)
 FROM CUSTOMER) +
 SUPPLIER.CDSUPPLIER AS CDCUSTOMER, SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE, '' AS NMADRESS
 FROM SUPPLIER

 --D
UPDATE REQUEST
SET DTDELIVER = DateAdd("d", 30, DTREQUEST)
WHERE DATEDIFF(day, DTREQUEST, DTDELIVER) < 10
AND VLTOTAL < 10000




-----------------------------------TESTES------------------------------
--A 
--INSERT INTO REQUEST(CDREQUEST, DTREQUEST, CDCUSTOMER, DTDELIVER, VLTOTAL)
--VALUES (329, '2003-06-01', 1, '2003-06-22', 600)

--SELECT * FROM REQUEST