--A 
SELECT P.NMPRODUCT, 
COUNT(DISTINCT(PR.CDREQUEST)) AS VZVENDIDO
FROM PRODUCT P 
INNER JOIN PRODUCTREQUEST PR ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY P.NMPRODUCT

--B 
SELECT S.NMSUPPLIER, 
COUNT(PR.CDPRODUCT) AS VZVENDIDO
FROM SUPPLIER S 
INNER JOIN PRODUCT P ON S.CDSUPPLIER=P.CDSUPPLIER
INNER JOIN PRODUCTREQUEST PR ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY S.NMSUPPLIER

--C
SELECT S.NMSUPPLIER, P.NMPRODUCT,
SUM(PR.QTAMOUNT) AS VZTOTALVENDIDO

FROM SUPPLIER S 
INNER JOIN PRODUCT P ON S.CDSUPPLIER=P.CDSUPPLIER
INNER JOIN PRODUCTREQUEST PR ON P.CDSUPPLIER=S.CDSUPPLIER

GROUP BY ROLLUP((NMSUPPLIER),(NMPRODUCT))

--D
SELECT C.NMCUSTOMER, P.NMPRODUCT,
SUM(R.VLTOTAL) AS TOTALPRODU
FROM REQUEST R
INNER JOIN CUSTOMER C ON R.CDCUSTOMER=C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST=PR.CDREQUEST
INNER JOIN PRODUCT P ON PR.CDPRODUCT=P.CDPRODUCT

GROUP BY ROLLUP(( NMCUSTOMER),(NMPRODUCT))

--E
SELECT C.NMCUSTOMER, C.IDFONE, PR.CDPRODUCT
FROM REQUEST R 
INNER JOIN CUSTOMER C ON R.CDCUSTOMER = C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST PR ON R.CDREQUEST = PR.CDREQUEST

WHERE PR.CDPRODUCT IS NULL

--F
SELECT S.NMSUPPLIER, S.IDFONE, P.NMPRODUCT
FROM PRODUCT P
INNER JOIN SUPPLIER S ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.NMPRODUCT LIKE '%leite em po%'
OR P.NMPRODUCT LIKE '%agua mineral%'

--G
SELECT P.NMPRODUCT, S.NMSUPPLIER,
SUM(PR.CDPRODUCT) AS PRODVENDIDO 

FROM SUPPLIER S
INNER JOIN PRODUCT P ON S.CDSUPPLIER=P.CDSUPPLIER
INNER JOIN PRODUCTREQUEST PR ON P.CDSUPPLIER=S.CDSUPPLIER


WHERE (PR.CDPRODUCT) > 3
GROUP BY P.NMPRODUCT, S.NMSUPPLIER


