--a (falta filtrar por maior de 15 )
SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, PRODUCT.VLPRICE, 
(VLPRICE-(VLPRICE* 0.1)) AS VLDESCT1, (VLPRICE-(VLPRICE* 0.2)) AS VLDESCT2,
(VLPRICE-(VLPRICE* 0.3)) AS VLDESCT3
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
WHERE (VLPRICE-(VLPRICE* 0.1)) > 15
ORDER BY VLPRICE, NMPRODUCT

--b
SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, 
PRODUCT.VLPRICE, (PRODUCT.VLPRICE* PRODUCT.QTSTOCK) AS TOTALSTOCK, 
((PRODUCT.QTSTOCK * 2)*PRODUCT.VLPRICE) AS TOTALSTOCK2
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
WHERE  (PRODUCT.VLPRICE* PRODUCT.QTSTOCK) > 1200
ORDER BY SUPPLIER.NMSUPPLIER

--c 
SELECT CDCUSTOMER, NMCUSTOMER, IDFONE, NMADRESS
FROM CUSTOMER
WHERE IDFONE IS NOT NULL
AND NMCUSTOMER LIKE 'J%'
ORDER BY NMCUSTOMER

--d
SELECT PRODUCT.NMPRODUCT, PRODUCT.VLPRICE, SUPPLIER.NMSUPPLIER
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
WHERE SUPPLIER.NMSUPPLIER LIKE '%ica%'

--e
SELECT SUPPLIER.NMSUPPLIER, SUPPLIER.IDFONE, PRODUCT.NMPRODUCT, PRODUCT.VLPRICE, 
(PRODUCT.VLPRICE* PRODUCT.QTSTOCK) AS TOTALSTOCK
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
WHERE PRODUCT.NMPRODUCT LIKE 'S%'
AND PRODUCT.VLPRICE > 50
ORDER BY SUPPLIER.NMSUPPLIER, PRODUCT.VLPRICE

--F

SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, REQUEST.DTREQUEST, 
REQUEST.DTDELIVER, PRODUCTREQUEST.QTAMOUNT, PRODUCTREQUEST.VLUNITARY, REQUEST.VLTOTAL
FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT

WHERE PRODUCTREQUEST.QTAMOUNT < 600
AND 
 REQUEST.DTREQUEST BETWEEN '2003-08-01' AND '2003-08-31'
AND PRODUCT.NMPRODUCT LIKE 'M%'


--G
SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, 
REQUEST.DTREQUEST, REQUEST.DTDELIVER, REQUEST.VLTOTAL
FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER

WHERE SUPPLIER.IDFONE LIKE '(011)%'
AND PRODUCT.VLPRICE > 20

