--a (falta filtrar por maior de 15 )
SELECT PRODUCT.NMPRODUCT, SUPPLIER.NMSUPPLIER, PRODUCT.VLPRICE, 
(VLPRICE-(VLPRICE* 0.1)) AS VLDESCT1, (VLPRICE-(VLPRICE* 0.2)) AS VLDESCT2,
(VLPRICE-(VLPRICE* 0.3)) AS VLDESCT3
FROM PRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER
ORDER BY VLPRICE, NMPRODUCT
