-- Criar tabelas

USE LISTA1

CREATE TABLE COSTUMER (
	CDCUSTOMER INT IDENTITY(1,1),
	NMCUSTOMER VARCHAR(255),
	NRFONE NUMERIC(12),
	DSADRESS VARCHAR(255)
)

CREATE TABLE REQUEST(
	CDREQUEST INT IDENTITY(1,1),
	DTREQUEST DATE,
	CDCOSTUMER INTEGER,
	DTDELIVER DATE,
	VLTOTAL INTEGER
)

CREATE TABLE PRODUCTREQUEST (
	CDREQUEST INTEGER,
	CDPRODUCT INTEGER,
	QTDAMOUNT INTEGER,
	VLUNITARY NUMERIC(10,2),
)

CREATE TABLE PRODUCT (
	CDPRODUCT INT IDENTITY(1,1),
	NMPRODUCT VARCHAR(255),
	CDSUPPLIER INTEGER,
	VLPRICE MONEY,
	QTSTOCK INTEGER
)

CREATE TABLE SUPPLIER (
	CDSUPPLIER INT IDENTITY(1,1),
	NMSUPPLIER VARCHAR(255),
	NRFONE NUMERIC(12)
)

--Inserir not nulls
USE LISTA1

ALTER TABLE COSTUMER 
ALTER COLUMN NMCUSTOMER VARCHAR (255) NOT NULL
ALTER TABLE COSTUMER 
ALTER COLUMN NRFONE NUMERIC(12) NOT NULL
ALTER TABLE COSTUMER 
ALTER COLUMN DSADRESS VARCHAR(255) NOT NULL

ALTER TABLE PRODUCT
ALTER COLUMN NMPRODUCT VARCHAR (255) NOT NULL
ALTER TABLE PRODUCT
ALTER COLUMN VLPRICE MONEY  NOT NULL
ALTER TABLE PRODUCT
ALTER COLUMN QTSTOCK INTEGER NOT NULL

ALTER TABLE PRODUCTREQUEST
ALTER COLUMN CDREQUEST INT NOT NULL
ALTER TABLE PRODUCTREQUEST
ALTER COLUMN CDPRODUCT INT NOT NULL
ALTER TABLE PRODUCTREQUEST
ALTER COLUMN QTDAMOUNT INTEGER NOT NULL
ALTER TABLE PRODUCTREQUEST
ALTER COLUMN VLUNITARY NUMERIC(10,2) NOT NULL

ALTER TABLE REQUEST
ALTER COLUMN CDREQUEST INT NOT NULL
ALTER TABLE REQUEST
ALTER COLUMN CDCOSTUMER INT NOT NULL
ALTER TABLE REQUEST
ALTER COLUMN DTREQUEST DATE NOT NULL
ALTER TABLE REQUEST
ALTER COLUMN DTDELIVER DATE NOT NULL
ALTER TABLE REQUEST
ALTER COLUMN VLTOTAL INTEGER NOT NULL

ALTER TABLE SUPPLIER
ALTER COLUMN NMSUPPLIER VARCHAR(255) NOT NULL
ALTER TABLE SUPPLIER
ALTER COLUMN NRFONE NUMERIC(12) NOT NULL


--Inserir chaves primarias

USE LISTA1

ALTER TABLE COSTUMER
ADD PRIMARY KEY (CDCUSTOMER)

ALTER TABLE REQUEST 
ADD PRIMARY KEY (CDREQUEST)

ALTER TABLE PRODUCT
ADD PRIMARY KEY (CDPRODUCT)

ALTER TABLE SUPPLIER
ADD PRIMARY KEY (CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST
ADD PRIMARY KEY (CDREQUEST, CDPRODUCT)

--Inserir chaves estrangeiras

USE LISTA1

ALTER TABLE REQUEST 
ADD CONSTRAINT FK_COSTUMER FOREIGN KEY (CDCOSTUMER) REFERENCES COSTUMER(CDCUSTOMER)

ALTER TABLE PRODUCT 
ADD CONSTRAINT FK_SUPPLIER FOREIGN KEY (CDSUPPLIER) REFERENCES SUPPLIER(CDSUPPLIER)

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (CDPRODUCT) REFERENCES PRODUCT(CDPRODUCT)
ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_REQUEST FOREIGN KEY (CDREQUEST) REFERENCES REQUEST(CDREQUEST)

--Criar indices das chaves estrangeiras
USE LISTA1

CREATE INDEX ID_FK_PRODUCT ON PRODUCT (CDSUPPLIER)
CREATE INDEX ID_FK_COSTUMER ON REQUEST (CDCOSTUMER)

--Adicionar campo endereço na tabele supplier
USE LISTA1

ALTER TABLE SUPPLIER
ADD SUPADRESS VARCHAR(255) NOT NULL;

--Inserção de novo cliente
USE LISTA1

INSERT INTO COSTUMER (NMCUSTOMER, NRFONE, DSADRESS) 
VALUES ('Fabiano', '99879375', 'Rua Tijucas, 110, Centro, Joinville – S.C');

--Inserção do novo pedido
USE LISTA1

INSERT INTO REQUEST(DTREQUEST, CDCUSTOMER, DTDELIVER, VLTOTAL) 
VALUES ('2008-01-31', 1, '2008-02-05', 54.00)

SELECT
R.CDREQUEST,
R.DTREQUEST,
R.CDCUSTOMER,
R.DTDELIVER,
R.VLTOTAL,
C.NMCUSTOMER
 
FROM REQUEST R
        INNER JOIN COSTUMER C ON R.CDCUSTOMER = C.CDCUSTOMER
;
 
-- i)


--Alteração no numero costumer 
USE LISTA1

UPDATE COSTUMER
SET NRFONE = 99012567
WHERE CDCUSTOMER = 1;

--Deletando request  pelo id
USE LISTA1
DELETE FROM REQUEST WHERE CDREQUEST=1;

--Deletando costumer  pelo id
USE LISTA1
DELETE FROM COSTUMER WHERE CDCUSTOMER=1;

--Apagando tables
DROP TABLE dbo.PRODUCTREQUEST
DROP TABLE dbo.REQUEST
DROP TABLE dbo.PRODUCT
DROP TABLE dbo.SUPPLIER
DROP TABLE dbo.COSTUMER