--A
SELECT DISTINCT PRODUCT.NMPRODUCT FROM PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT

SELECT PRODUCT.NMPRODUCT
FROM PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
GROUP BY NMPRODUCT

--B
SELECT PRODUCT.NMPRODUCT, COUNT(DISTINCT (PRODUCTREQUEST.CDREQUEST)) AS VEZESPEDIDA,
SUM(PRODUCTREQUEST.QTAMOUNT) AS TOTAL
FROM PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT=PRODUCT.CDPRODUCT
GROUP BY NMPRODUCT

--C
SELECT SUPPLIER.NMSUPPLIER, 
SUM(PRODUCT.QTSTOCK) AS TOTALSTOCK,
COUNT(PRODUCT.CDPRODUCT) AS TOTALPRODUCT, 
AVG(PRODUCT.VLPRICE) AS MEDIAPRICE

FROM SUPPLIER
INNER JOIN PRODUCT ON SUPPLIER.CDSUPPLIER=PRODUCT.CDSUPPLIER
GROUP BY NMSUPPLIER

--D
SELECT CUSTOMER.NMCUSTOMER, CUSTOMER.IDFONE,
 MAX(REQUEST.VLTOTAL) AS MAIORCOMPRA,
 MIN(REQUEST.VLTOTAL) AS MENORCOMPRA,
 SUM(REQUEST.VLTOTAL) AS TOTALCOMPRA,
 AVG(REQUEST.VLTOTAL) AS MEDIACOMPRA
FROM CUSTOMER
INNER JOIN REQUEST ON CUSTOMER.CDCUSTOMER=REQUEST.CDCUSTOMER

GROUP BY NMCUSTOMER, IDFONE
ORDER BY MAX(VLTOTAL) DESC

--E
SELECT 
REQUEST.DTREQUEST , CUSTOMER.NMCUSTOMER, 
COUNT(DISTINCT( PRODUCTREQUEST.CDPRODUCT)) AS PRODUCTDISTINT,
SUM(PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS TOTALREQUEST,
AVG(PRODUCTREQUEST.QTAMOUNT * PRODUCTREQUEST.VLUNITARY) AS MEDIA

FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST=PRODUCTREQUEST.CDREQUEST

GROUP BY NMCUSTOMER, DTREQUEST
ORDER BY PRODUCTDISTINT

--F
SELECT SUPPLIER.NMSUPPLIER, 
COUNT(PRODUCT.CDSUPPLIER) AS PRODSUP

FROM SUPPLIER
INNER JOIN PRODUCT ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER

WHERE (PRODUCT.CDSUPPLIER) > 1

GROUP BY NMSUPPLIER

--G
SELECT PRODUCT.NMPRODUCT, 
COUNT(REQUEST.CDPRODUCT) AS VEZESPEDIDO,
SUM(PRODUCTREQUEST.QTAMOUNT) AS TOTALPEDIDO

FROM PRODUCTREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT=PRODUCT.CDPRODUCT

WHERE (PRODUCTREQUEST.CDPRODUCT) < 2
GROUP BY NMPRODUCT

--H
SELECT CUSTOMER.NMCUSTOMER, PRODUCT.NMPRODUCT, 
SUM (PRODUCTREQUEST.VLUNITARY) AS TOTALPRODUCT,
SUPPLIER.NMSUPPLIER

FROM REQUEST
INNER JOIN CUSTOMER ON REQUEST.CDCUSTOMER = CUSTOMER.CDCUSTOMER
INNER JOIN PRODUCTREQUEST ON REQUEST.CDREQUEST = PRODUCTREQUEST.CDREQUEST
INNER JOIN PRODUCT ON PRODUCTREQUEST.CDPRODUCT = PRODUCT.CDPRODUCT
INNER JOIN SUPPLIER ON PRODUCT.CDSUPPLIER=SUPPLIER.CDSUPPLIER


WHERE  (PRODUCTREQUEST.VLUNITARY) > 1.000

GROUP BY NMPRODUCT, NMSUPPLIER, NMCUSTOMER
ORDER BY  NMCUSTOMER, NMPRODUCT